# Generated by Django 5.2 on 2025-09-09 19:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalArmazenamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_armazenamento', models.CharField(choices=[('sede_palmas', 'SEDE - PALMAS'), ('inspetoria_araguaina', 'INSPETORIA DE ARAGUAÍNA'), ('inspetoria_augustinopolis', 'INSPETORIA DE AUGUSTINÓPOLIS'), ('inspetoria_dianopolis', 'INSPETORIA DE DIANÓPOLIS'), ('inspetoria_guarai', 'INSPETORIA DE GUARAÍ'), ('inspetoria_gurupi', 'INSPETORIA DE GURUPI'), ('inspetoria_paraiso_tocantins', 'INSPETORIA DE PARAÍSO DO TOCANTINS'), ('inspetoria_porto_nacional', 'INSPETORIA DE PORTO NACIONAL')], default='sede_palmas', help_text='Unidade do CREA-TO onde está o armazenamento', max_length=30, verbose_name='Local de Armazenamento')),
                ('armario', models.CharField(help_text='Número do armário (apenas números)', max_length=50, verbose_name='Armário')),
                ('prateleira', models.CharField(help_text='Número da prateleira (apenas números)', max_length=50, verbose_name='Prateleira')),
                ('caixa', models.CharField(help_text='Número da caixa (apenas números)', max_length=50, verbose_name='Caixa')),
            ],
            options={
                'verbose_name': 'Local de Armazenamento',
                'verbose_name_plural': 'Locais de Armazenamento',
                'ordering': ['local_armazenamento', 'armario', 'prateleira', 'caixa'],
                'unique_together': {('local_armazenamento', 'armario', 'prateleira', 'caixa')},
            },
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número único do protocolo', max_length=50, unique=True, verbose_name='Número de Protocolo')),
                ('data_emissao', models.DateField(auto_now_add=True, help_text='Data de criação do protocolo', verbose_name='Data de Emissão')),
                ('cpf_cnpj', models.CharField(blank=True, help_text='CPF (11 dígitos) ou CNPJ (14 dígitos) - obrigatório para processos finalísticos', max_length=18, null=True, validators=[django.core.validators.RegexValidator(message='CPF deve ter 11 dígitos ou CNPJ deve ter 14 dígitos', regex='^\\d{11}|\\d{14}$')], verbose_name='CPF/CNPJ')),
                ('tipo', models.CharField(choices=[('finalistico_pf', 'Processo Finalístico - Pessoa Física'), ('finalistico_pj', 'Processo Finalístico - Pessoa Jurídica'), ('administrativo', 'Processo Administrativo')], help_text='Tipo de processo a ser protocolado', max_length=20, verbose_name='Tipo de Processo')),
                ('armario', models.CharField(blank=True, help_text='Número do armário (apenas números)', max_length=10, verbose_name='Armário')),
                ('prateleira', models.CharField(blank=True, help_text='Número da prateleira (apenas números)', max_length=10, verbose_name='Prateleira')),
                ('caixa', models.CharField(blank=True, help_text='Número da caixa (apenas números)', max_length=10, verbose_name='Caixa')),
                ('unidade_crea', models.CharField(choices=[('sede_palmas', 'SEDE - PALMAS'), ('inspetoria_araguaina', 'INSPETORIA DE ARAGUAÍNA'), ('inspetoria_augustinopolis', 'INSPETORIA DE AUGUSTINÓPOLIS'), ('inspetoria_dianopolis', 'INSPETORIA DE DIANÓPOLIS'), ('inspetoria_guarai', 'INSPETORIA DE GUARAÍ'), ('inspetoria_gurupi', 'INSPETORIA DE GURUPI'), ('inspetoria_paraiso_tocantins', 'INSPETORIA DE PARAÍSO DO TOCANTINS'), ('inspetoria_porto_nacional', 'INSPETORIA DE PORTO NACIONAL')], default='sede_palmas', help_text='Unidade do CREA-TO responsável pelo protocolo', max_length=30, verbose_name='Unidade CREA-TO')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais sobre o protocolo', verbose_name='Observações')),
                ('protocolo_sitac', models.CharField(blank=True, help_text='Número de protocolo retornado pela API do SITAC', max_length=50, null=True, verbose_name='Protocolo SITAC')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocolos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Protocolo',
                'verbose_name_plural': 'Protocolos',
                'ordering': ['-data_emissao', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('finalistico_pf', 'Processo Finalístico - Pessoa Física'), ('finalistico_pj', 'Processo Finalístico - Pessoa Jurídica'), ('administrativo', 'Processo Administrativo')], help_text='Categoria do processo ao qual este tipo de documento pertence', max_length=20, verbose_name='Categoria do Processo')),
                ('nome', models.CharField(help_text='Nome do tipo de documento', max_length=100, verbose_name='Nome do Documento')),
                ('ativo', models.BooleanField(default=True, help_text='Se este tipo de documento está ativo', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'ordering': ['categoria', 'nome'],
                'unique_together': {('categoria', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre este documento', verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='protocolos.protocolo', verbose_name='Protocolo')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocolos.tipodocumento', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
