# Generated by Django 5.2 on 2025-08-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0002_alter_protocolo_criado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolo',
            name='ativo',
        ),
        migrations.AddField(
            model_name='protocolo',
            name='protocolo_sitac',
            field=models.CharField(blank=True, help_text='Número de protocolo retornado pela API do SITAC', max_length=50, null=True, verbose_name='Protocolo SITAC'),
        ),
    ]
