# Generated by Django 5.2 on 2025-09-03 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0003_remove_protocolo_ativo_protocolo_protocolo_sitac'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolo',
            name='unidade_crea',
            field=models.CharField(choices=[('sede_palmas', 'SEDE - PALMAS'), ('inspetoria_araguaina', 'INSPETORIA DE ARAGUAÍNA'), ('inspetoria_augustinopolis', 'INSPETORIA DE AUGUSTINÓPOLIS'), ('inspetoria_dianopolis', 'INSPETORIA DE DIANÓPOLIS'), ('inspetoria_guarai', 'INSPETORIA DE GUARAÍ'), ('inspetoria_gurupi', 'INSPETORIA DE GURUPI'), ('inspetoria_paraiso_tocantins', 'INSPETORIA DE PARAÍSO DO TOCANTINS'), ('inspetoria_porto_nacional', 'INSPETORIA DE PORTO NACIONAL')], default='sede_palmas', help_text='Unidade do CREA-TO responsável pelo protocolo', max_length=30, verbose_name='Unidade CREA-TO'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='local_armazenamento',
            field=models.CharField(blank=True, help_text='Ex: CAIXA X, FILEIRA X, FACE X (campo legado)', max_length=100, verbose_name='Local de Armazenamento'),
        ),
        migrations.CreateModel(
            name='LocalArmazenamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armario', models.CharField(help_text='Número ou identificação do armário', max_length=50, verbose_name='Armário')),
                ('prateleira', models.CharField(help_text='Número ou identificação da prateleira', max_length=50, verbose_name='Prateleira')),
                ('caixa', models.CharField(help_text='Número ou identificação da caixa', max_length=50, verbose_name='Caixa')),
            ],
            options={
                'verbose_name': 'Local de Armazenamento',
                'verbose_name_plural': 'Locais de Armazenamento',
                'ordering': ['armario', 'prateleira', 'caixa'],
                'unique_together': {('armario', 'prateleira', 'caixa')},
            },
        ),
        migrations.AddField(
            model_name='protocolo',
            name='local_armazenamento_detalhado',
            field=models.ForeignKey(blank=True, help_text='Local físico detalhado onde o protocolo está armazenado (Armário, Prateleira, Caixa)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='protocolos.localarmazenamento', verbose_name='Local de Armazenamento Detalhado'),
        ),
    ]
