# Generated by Django 5.2 on 2025-09-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0004_protocolo_unidade_crea_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localarmazenamento',
            options={'ordering': ['local_armazenamento', 'armario', 'prateleira', 'caixa'], 'verbose_name': 'Local de Armazenamento', 'verbose_name_plural': 'Locais de Armazenamento'},
        ),
        migrations.AlterUniqueTogether(
            name='localarmazenamento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='localarmazenamento',
            name='local_armazenamento',
            field=models.CharField(choices=[('sede_palmas', 'SEDE - PALMAS'), ('inspetoria_araguaina', 'INSPETORIA DE ARAGUAÍNA'), ('inspetoria_augustinopolis', 'INSPETORIA DE AUGUSTINÓPOLIS'), ('inspetoria_dianopolis', 'INSPETORIA DE DIANÓPOLIS'), ('inspetoria_guarai', 'INSPETORIA DE GUARAÍ'), ('inspetoria_gurupi', 'INSPETORIA DE GURUPI'), ('inspetoria_paraiso_tocantins', 'INSPETORIA DE PARAÍSO DO TOCANTINS'), ('inspetoria_porto_nacional', 'INSPETORIA DE PORTO NACIONAL')], default='sede_palmas', help_text='Unidade do CREA-TO onde está o armazenamento', max_length=30, verbose_name='Local de Armazenamento'),
        ),
        migrations.AlterField(
            model_name='localarmazenamento',
            name='armario',
            field=models.CharField(help_text='Número do armário (apenas números)', max_length=50, verbose_name='Armário'),
        ),
        migrations.AlterField(
            model_name='localarmazenamento',
            name='caixa',
            field=models.CharField(help_text='Número da caixa (apenas números)', max_length=50, verbose_name='Caixa'),
        ),
        migrations.AlterField(
            model_name='localarmazenamento',
            name='prateleira',
            field=models.CharField(help_text='Número da prateleira (apenas números)', max_length=50, verbose_name='Prateleira'),
        ),
        migrations.AlterUniqueTogether(
            name='localarmazenamento',
            unique_together={('local_armazenamento', 'armario', 'prateleira', 'caixa')},
        ),
    ]
