# Generated by Django 5.2 on 2025-09-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0005_alter_localarmazenamento_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolo',
            name='local_armazenamento_detalhado',
        ),
        migrations.AddField(
            model_name='protocolo',
            name='armario',
            field=models.CharField(blank=True, help_text='Número do armário (apenas números)', max_length=10, verbose_name='Armário'),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='caixa',
            field=models.CharField(blank=True, help_text='Número da caixa (apenas números)', max_length=10, verbose_name='Caixa'),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='prateleira',
            field=models.CharField(blank=True, help_text='Número da prateleira (apenas números)', max_length=10, verbose_name='Prateleira'),
        ),
    ]
