# Generated by Django 5.2 on 2025-09-03 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0006_remove_protocolo_local_armazenamento_detalhado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolo',
            name='local_armazenamento',
        ),
    ]
