# Generated by Django 5.2 on 2025-08-26 17:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(help_text='000.000.000-00', max_length=14, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, help_text='(00) 00000-0000', max_length=15, verbose_name='Telefone')),
                ('tipo_usuario', models.CharField(choices=[('engenheiro', 'Engenheiro'), ('arquiteto', 'Arquiteto'), ('tecnico', 'Técnico'), ('estudante', 'Estudante'), ('funcionario', 'Funcionário CREA-TO'), ('outro', 'Outro')], default='engenheiro', max_length=20, verbose_name='Tipo de Usuário')),
                ('registro_profissional', models.CharField(blank=True, help_text='Número do registro no CREA', max_length=20, verbose_name='Registro Profissional')),
                ('empresa', models.CharField(blank=True, max_length=200, verbose_name='Empresa/Instituição')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo/Função')),
                ('permissao', models.CharField(choices=[('visualizador', 'Visualizador'), ('editor', 'Editor'), ('publicador', 'Publicador'), ('admin', 'Administrador')], default='visualizador', max_length=20, verbose_name='Nível de Permissão')),
                ('pode_publicar', models.BooleanField(default=False, verbose_name='Pode Publicar Atas')),
                ('pode_visualizar_sigiloso', models.BooleanField(default=False, verbose_name='Pode Visualizar Sigiloso')),
                ('documento_identidade', models.FileField(blank=True, null=True, upload_to='usuarios/documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Documento de Identidade')),
                ('comprovante_residencia', models.FileField(blank=True, null=True, upload_to='usuarios/documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Comprovante de Residência')),
                ('diploma_ou_certificado', models.FileField(blank=True, null=True, upload_to='usuarios/documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Diploma ou Certificado')),
                ('email_verificado', models.BooleanField(default=False, verbose_name='E-mail Verificado')),
                ('conta_aprovada', models.BooleanField(default=False, verbose_name='Conta Aprovada')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True, verbose_name='Último Acesso')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_aprovados', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
