# Generated by Django 5.2 on 2025-08-26 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilusuario_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='comprovante_residencia',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='diploma_ou_certificado',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='documento_identidade',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='email_verificado',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='pode_visualizar_sigiloso',
        ),
    ]
