# Generated by Django 5.2 on 2025-09-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_perfilusuario_comprovante_residencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='tipo_usuario',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='local',
            field=models.CharField(choices=[('sede_palmas', 'SEDE - PALMAS'), ('inspetoria_araguaina', 'INSPETORIA DE ARAGUAÍNA'), ('inspetoria_augustinopolis', 'INSPETORIA DE AUGUSTINÓPOLIS'), ('inspetoria_dianopolis', 'INSPETORIA DE DIANÓPOLIS'), ('inspetoria_guarai', 'INSPETORIA DE GUARAÍ'), ('inspetoria_gurupi', 'INSPETORIA DE GURUPI'), ('inspetoria_paraiso_tocantins', 'INSPETORIA DE PARAÍSO DO TOCANTINS'), ('inspetoria_porto_nacional', 'INSPETORIA DE PORTO NACIONAL')], default='sede_palmas', help_text='Unidade do CREA-TO onde o usuário trabalha', max_length=30, verbose_name='Local de Trabalho'),
        ),
    ]
